### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by sernyak9kolya** [sernyak9kolya/homepage#5]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by maykl25loki** [comment]
### Languages
German, English

### Honours

- **Mainz 05**
1. Second Bundesliga third-place promotion: 2003–04

- **Borussia Dortmund**
1. Bundesliga: 2010–11, 2011–12
2. DFB-Pokal: 2011–12
3. DFL-Supercup: 2013, 2014
4. UEFA Champions League runner-up: 2012–13

- **Liverpool**
1. UEFA Champions League: 2018–19
2. UEFA Super Cup: 2019
3. FIFA Club World Cup: 2019

- **Individual**
1. German Football Manager of the Year: 2011, 2012, 2019
2. Premier League Manager of the Month: September 2016, December 2018, March 2019, August 2019, September 2019, November 2019, December 2019, January 2020
3. Deutscher Fernsehpreis (German Television Award): 2006, 2010
4. Mainzer Medienpreis (Mainz Media Award): 2018
5. Onze d'Or Coach of the Year: 2018–19
6. The Best FIFA Men's Coach: 2019
7. IFFHS World's Best Club Coach: 2019
8. World Soccer Awards World Manager of the Year: 2019
9. Globe Soccer Awards Best Coach of the Year: 2019
10. League Managers Association (LMA) Hall of Fame

### Personal Quotes

> [on the difference between himself and Arsène Wenger] He likes having the ball, playing football, passes. It's like an orchestra. But it's a silent song. But I like heavy metal more. I always want it loud.

> If you lose a game, everyone asks why this player didn't play. If we win, nobody asks.

> [on Mats Hummels' continuous injury problems] We will wait for him like a good wife waiting for her husband who is in jail.

> [New signing Henrikh] Mkhitaryan fits us like an arse on a bucket. What he offers is exactly what we need.

> If I would lose control at home as much as I do in the stadium at times, my wife and I probably wouldn't be together anymore.

> For me, the pitch is like Las Vegas. What happens on the pitch stays on the pitch.
