### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by sernyak9kolya** [sernyak9kolya/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by maykl25loki** [comment]
- **1967**
Jürgen Norbert Klopp was born on June 16, 1967, in Stuttgart.
- **1990**
In 1990, Jürgen Klopp was signed by the German football club, ‘Mainz 05,’ as a player.
- **2001**
In February 2001, Klopp retired as a player, from the ‘Mainz 05,’ and was appointed as their coach.
- **2005**
Klopp has made appearances on TV shows.
- **2005**
Jürgen Klopp has married twice.
- **2008**
In 2008, Jürgen Klopp was appointed as the manager of the Borussia Dortmund.
- **2015**
In October 2015, Jürgen Klopp was appointed as the manager of the Liverpool Football Club.
- **2019**
On 1st June 2019, Klopp with Liverpool FC won the '2019 UEFA Champions League Finals'.
